### ISSUE TITLE
JNode hangs at boot time in Virtual Box (Mac)

### ISSUE THREAD

**Issue by vincenzofehring** [jnode/jnode#36]
Upon downloading the source and building a disk image, I launched it in my Virtual Box install on my Mac. The system boots up fine to the boot menu. No matter what option I select, it hangs on the screen indefinitely.
![jnode hang](https://cloud.githubusercontent.com/assets/671972/3486318/906f0ca4-042e-11e4-8414-dfd83254183a.png)
Hopefully there is a workaround, because I would love to be able to test this OS and even work on some new features.

**Comment by IvoClarysse** [comment]
I'm able to run JNode (commit 049868e9a7b5f9181332b7ab816f2cc4b1c4e7e3) on Virtualbox 4.3.26, Mac, Intel Core i5 with VT-x and Nested Paging enabled, but only when launching the jnode-x86-lite.iso image in a 64-bit virtual machine.

**Comment by emarkus** [comment]
thank you

**Comment by LSantha** [comment]
Appears to be answered, I'm closing the issue.
