### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by adolfo2103** [jnode/jnode#37]
hello i like participe in this project because i follow one year ago please somebody tell me how i can contribute in this tnanks

**Comment by LSantha** [comment]
@adolfo2103, please let me know if you still intend to participate in JNode development.

**Comment by adolfo2103** [comment]
Absolutely because i still development and inplement new functionalities in
this project for i hope have a powerfull and better java operative system
that can be exist

**Comment by LSantha** [comment]
Excellent. There are many ways you can contribute, starting from testing, coding and so on, it depends on you and what you would like to do. You can think of programming domain related to JNode which is familiar to you or you want to learn about it. Actually experimenting with JNode and working on it can be a very valuable learning experience.

Did you have a chance to run JNode already on bare metal or in a VM? 
Getting the source code and getting familiar with it and the documentation on jnode.org, building JNode and running it on various devices can be good activities for starting up.

**Comment by adolfo2103** [comment]
ok i still read and testing things of the project and development new
modules for asembly in the core project soon  i send you my results

regards


On Sun, Feb 7, 2016 at 2:42 PM, Levente Santha <notifications@github.com>
wrote:

> Closed #37 <https://github.com/jnode/jnode/issues/37>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jnode/jnode/issues/37#event-542277885>.
>



-- 

William Adolfo Urrea Varon Software Developer
Software Developer Unix-Linux and mobile  Platforms
3045255856
http://willia <http://www.heroeslabs.info>msite.tk

**Comment by LSantha** [comment]
Sounds good!
Feel free to open a new issue when you want to send it.
