### ISSUE TITLE
Qemu on Linux fails to boot

### ISSUE THREAD

**Issue by ghost** [jnode/jnode#42]
Tried to boot JNode on Linux Ubuntu 15 and Linux Mint 9.
Both could not boot.  Is there something to be done to make it recognizable by QEMU?

**Comment by LSantha** [comment]
@host, I'm booting JNode with QEMU 2.3 on Ubuntu 15.10 with no problem.
Example command:
qemu-system-i386 -enable-kvm -vga vmware -m 1024M -cdrom /path/to/jnode/source/tree/all/build/cdroms/jnode-x86-lite.iso

**Comment by LSantha** [comment]
Cannot reproduce.
