### ISSUE TITLE
jconsole sun.tools.console.JConsole throws AccessControlException

### ISSUE THREAD

**Issue by dagdd** [jnode/jnode#43]
After starting up jconsole it throws AccessControlException java.lang.RuntimePermission accessDeclaredMember not granted du to sun.tools.console.InternalDialog$MastheadIcon
Screen dumps attached.
<img width="1176" alt="skjermbilde 2016-01-09 kl 20 16 25" src="https://cloud.githubusercontent.com/assets/16381848/12217996/ca2954d0-b711-11e5-8dbb-978754800a8c.png">
<img width="1148" alt="skjermbilde 2016-01-09 kl 20 17 50" src="https://cloud.githubusercontent.com/assets/16381848/12218008/da3e99c0-b711-11e5-99a1-bb8ee8e2af05.png">

**Comment by dagdd** [comment]
Workaround for the error:
Adding
permission class="java.lang.RuntimePermission" name="accessDeclaredMembers"
to the descriptor file: core/descriptors/sun.tools.xml
improves the jconsole. See the attached file:
<img width="1148" alt="skjermbilde 2016-01-10 kl 09 38 12" src="https://cloud.githubusercontent.com/assets/16381848/12220784/40385f36-b780-11e5-9658-dfa24777d918.png">

**Comment by LSantha** [comment]
Fixed with commits:
https://github.com/jnode/classlib6/commit/be154632eff2dee88832d3acba28ca458feff0a0
https://github.com/jnode/jnode/commit/22c852e60b59f9bca68b1b7a9550d124a6886be2

@dagdd, could you please check this if it works for you?

**Comment by dagdd** [comment]
It works now. I am closing this issue.
