### ISSUE TITLE
org.jnode.wm.VmExit: VM exit, status: 0  may be thrown

### ISSUE THREAD

**Issue by dagdd** [jnode/jnode#49]
Consider the following case:
You are running a standalone swing/awt application directly from console (eg. sconsole)
Then you are closing the application. After closing the application you press Shift-Alt-F12 to restore console.
Then you get the exception.
See attached screenshot:
If you do not close the application and press Shift-Alt-F12, no exception is thrown.
<img width="1176" alt="skjermbilde 2016-01-16 kl 20 54 43" src="https://cloud.githubusercontent.com/assets/16381848/12374350/19ff177e-bc99-11e5-8172-fbf46826ade6.png">
<img width="1176" alt="skjermbilde 2016-01-16 kl 21 11 23" src="https://cloud.githubusercontent.com/assets/16381848/12374352/22c7bbf4-bc99-11e5-830c-e2fda04ad699.png">
<img width="1176" alt="skjermbilde 2016-01-16 kl 21 12 18" src="https://cloud.githubusercontent.com/assets/16381848/12374354/28624be2-bc99-11e5-8680-960527b5ee5f.png">

**Comment by dagdd** [comment]
Tested VmExit
No stack trace is written for the following commands:
AWTDemo
AWTMenuBuilderTest
AWTTest
JTreeTest
JTableTest
JTreeTest
SwingMenuTest
SwingTest
TextFieldTest
ThinTest
MouseEventTest
RobotTest
However, stack trace is written for the following commands after closing and return to the console:
sconsole
Boxworld
Rubik
Tetris
jconsole
policytool
jpartition -s

**Comment by LSantha** [comment]
@dagdd, I cannot reproduce the issue for the remaining commands that you reported as still manifesting the bug.
Due to the nature of the programs and the implementation of the fix, I would expect that all those commands would uniformly either expose the bug or not.
Under what conditions did you those stack traces?

**Comment by dagdd** [comment]
When I am testing this issue again on the last version of JNode I am not able to reproduce the issue.
I am not able to explain why I got the issues in the earlier build of JNode. So I think this issue can be closed now. Thank you for  your attention.

**Comment by LSantha** [comment]
Thank you for confirming it.
