### ISSUE TITLE
Selecting AWTTest or AWTMenuTest results in the same application

### ISSUE THREAD

**Issue by dagdd** [jnode/jnode#53]
AWTTest starts in both cases. See the attached screenshot.
<img width="1176" alt="skjermbilde 2016-01-16 kl 22 43 18" src="https://cloud.githubusercontent.com/assets/16381848/12374682/90e0ae20-bca3-11e5-921e-7330fed5fba0.png">

**Comment by LSantha** [comment]
AWTMenuTest is an extension of AWTTest with a Window menu. 
I've added a File menu beside Window to make this more visible.

**Comment by dagdd** [comment]
Not a bug. Closing.
