### ISSUE TITLE
Startup class/method

### ISSUE THREAD

**Issue by GuzioMG** [jnode/jnode#65]
I want to know, which class is the startup one. I know, that (probably) the Nano Kernel is loading JavaVM and Java classes from OpenJDK, and then starts a startup class. So where the actuall OS starts?

**Comment by GuzioMG** [comment]
Also, if it's working other way, can you explain, how is it working?

**Comment by pisaiah** [comment]
Wouldn't it be [`org.jnode.boot.Main`](https://github.com/jnode/jnode/blob/master/core/src/core/org/jnode/boot/Main.java)

**Comment by GuzioMG** [comment]
Thank you, I'll check it!
